// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Font48.Models.Controls;

public partial class TbAction
{
    public int Id { get; set; }

    public int TestId { get; set; }

    public int ActionTypeId { get; set; }

    public DateTime? Created { get; set; }

    public double? FontSize { get; set; }

    public string FontName { get; set; }
}