// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Font48.Models.Controls;

public partial class TbControlType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }
}