// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Font48.Models.Controls;

public partial class TbControl
{
    public int Id { get; set; }

    public int ActionId { get; set; }

    public string ControlName { get; set; }

    public string ControlText { get; set; }

    public int? ControlTypeId { get; set; }

    public int? LocationX { get; set; }

    public int? LocationY { get; set; }

    public int? SizeX { get; set; }

    public int? SizeY { get; set; }

    public bool? IsAutoSize { get; set; }
}