// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Font48.Models.Controls;

public partial class TbTest
{
    public int Id { get; set; }

    public string TestName { get; set; }

    public string Description { get; set; }

    public DateTime? Created { get; set; }

    public decimal? FontSize { get; set; }

    public int? AppTypeId { get; set; }
}